name: Autodeploy
run-name: Run the deploy command
on:
  push:
    branches: [main]
jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node & deploy
      - name: Setup Node & deploy
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Make script file executable
        run: chmod +x extract.sh
      - name: Run the script
        run: ./extract.sh
      - name: Indent table and deploy
        run: |
          npm install
          npm run format
          npm run format
          npm run deploy
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "docs: deploy site"
          git push
